// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArV-3GzftfJLHlCXMqrTQVLqOichv3fTk',
    appId: '1:503736221490:web:ba315d61c845ca31d5212b',
    messagingSenderId: '503736221490',
    projectId: 'ween-2d99d',
    authDomain: 'ween-2d99d.firebaseapp.com',
    storageBucket: 'ween-2d99d.appspot.com',
    measurementId: 'G-DH1NR12N3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlvjvqDiXEPYmWj8p7FUEhiiki9DkFXA8',
    appId: '1:503736221490:android:035ee505099f8065d5212b',
    messagingSenderId: '503736221490',
    projectId: 'ween-2d99d',
    storageBucket: 'ween-2d99d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXV3XgGIaTh8-wOJdjjb54QOHgB0AU-fs',
    appId: '1:503736221490:ios:c7f9ef3377788d26d5212b',
    messagingSenderId: '503736221490',
    projectId: 'ween-2d99d',
    storageBucket: 'ween-2d99d.appspot.com',
    iosBundleId: 'com.example.ween',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXV3XgGIaTh8-wOJdjjb54QOHgB0AU-fs',
    appId: '1:503736221490:ios:3b2a528440886586d5212b',
    messagingSenderId: '503736221490',
    projectId: 'ween-2d99d',
    storageBucket: 'ween-2d99d.appspot.com',
    iosBundleId: 'com.example.ween.RunnerTests',
  );
}
